version: '3.6'
# Volumes are HOST directory and then CONTAINER directory

services:
  # Postgresql server
  database:
    image: postgres:13.3
    environment:
      - MAX_CONNECTIONS=125
      - SHARED_BUFFERS=4096MB
      - WORK_MEM=256MB
      - MAX_WORKER_PROCESSES=4
      - MAX_PARALLEL_WORKERS_PER_GATHER=2
      - MAX_PARALLEL_WORKERS=4
      - POSTGRES_PASSWORD=meuse
    command: postgres
    container_name: mkstack_database
    stop_grace_period: 30s
    stop_signal: SIGTERM
    volumes:
      - mediakraken_vol_postgresql:/var/lib/postgresql/data
    networks:
      - mediakraken_network
    restart: unless-stopped

  meuse:
    image: mediakraken/mkmeuse:dev2021_04
    environment:
      - MEUSE_CONFIGURATION=/mediakraken/meuse.cfg
    command: java -jar /app/meuse.jar
    container_name: mkstack_meuse
    stop_grace_period: 30s
    stop_signal: SIGTERM
    volumes:
      - mediakraken_vol_meuse:/mediakraken/cargo
    networks:
      - mediakraken_network
    ports:
      - "8855:8855"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:5.2
    stop_grace_period: 30s
    stop_signal: SIGTERM
    container_name: mkstack_pgadmin
    networks:
      - mediakraken_network
    ports:
      - "5050:5050"
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: spootdev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: metaman
      PGADMIN_DISABLE_POSTFIX: 1
    volumes:
      - mediakraken_vol_pgadmin:/var/lib/pgadmin

  portainer:
    image: portainer/portainer-ce:2.1.1-alpine
    command: -H unix:///var/run/docker.sock
    container_name: mkstack_portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portaineragent_agent_network

# Docker private networks
networks:
  # Twisted, Database and AMQP communications network
  mediakraken_network:
    driver: bridge
    name: mk_mediakraken_network
  # portainer stuff
  portaineragent_agent_network:
    driver: bridge
    name: mk_portainer_network

volumes:
  portainer_data:
  mediakraken_vol_meuse:
  mediakraken_vol_pgadmin:
  mediakraken_vol_postgresql: